_wandb:
    value:
        cli_version: 0.25.0
        e:
            myzqjbepnxmj8wzyh6d36dncjlut0gmn:
                args:
                    - --wandb_mode
                    - online
                    - --num_models
                    - "5"
                codePath: src\loss_comparison.py
                codePathLocal: src\loss_comparison.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "180007989248"
                        used: "150667780096"
                email: ma24m018@smail.iitm.ac.in
                executable: C:\Users\Ganga Sharan\OneDrive\Desktop\dl_project\Multi-Layer-Perceptron-for-Image-Classification\.venv\Scripts\python.exe
                git:
                    commit: 3eda2518ab39d39780a6f2e6c0fdd0e4b5bba5d5
                    remote: https://github.com/Neha-irongirl/Multi-Layer-Perceptron-for-Image-Classification.git
                host: LAPTOP-BQBRQ1PT
                memory:
                    total: "12593659904"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Ganga Sharan\OneDrive\Desktop\dl_project\Multi-Layer-Perceptron-for-Image-Classification\src\loss_comparison.py
                python: CPython 3.13.3
                root: C:\Users\Ganga Sharan\OneDrive\Desktop\dl_project\Multi-Layer-Perceptron-for-Image-Classification
                startedAt: "2026-02-26T15:16:40.801337Z"
                writerId: myzqjbepnxmj8wzyh6d36dncjlut0gmn
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
                - 61
                - 62
            "4": 3.13.3
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 15
hidden_layers:
    value: 3
hidden_size:
    value: 128
lr:
    value: 0.001
num_models:
    value: 5
seed:
    value: 42
target_acc:
    value: 0.9
wandb_entity:
    value: null
wandb_mode:
    value: online
wandb_project:
    value: loss-function-comparison
