_wandb:
    value:
        cli_version: 0.25.0
        e:
            1yy4606o2fxobos1kl7rbaoykrxtwngr:
                args:
                    - --run_sweep
                    - --sweep_config
                    - sweep_config.yaml
                    - --sweep_count
                    - "100"
                    - --wandb_project
                    - mnist-ann
                    - --wandb_mode
                    - online
                codePath: src\train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "180007989248"
                        used: "150819446784"
                email: ma24m018@smail.iitm.ac.in
                executable: C:\Users\Ganga Sharan\OneDrive\Desktop\dl_project\Multi-Layer-Perceptron-for-Image-Classification\.venv\Scripts\python.exe
                git:
                    commit: 3eda2518ab39d39780a6f2e6c0fdd0e4b5bba5d5
                    remote: https://github.com/Neha-irongirl/Multi-Layer-Perceptron-for-Image-Classification.git
                host: LAPTOP-BQBRQ1PT
                memory:
                    total: "12593659904"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Ganga Sharan\OneDrive\Desktop\dl_project\Multi-Layer-Perceptron-for-Image-Classification\src\train.py
                python: CPython 3.13.3
                root: C:\Users\Ganga Sharan\OneDrive\Desktop\dl_project\Multi-Layer-Perceptron-for-Image-Classification\src
                startedAt: "2026-02-26T11:36:00.161979Z"
                writerId: 1yy4606o2fxobos1kl7rbaoykrxtwngr
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 14
                - 61
                - 62
            "4": 3.13.3
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation_function:
    value: relu
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 10
initialization_method:
    value: he
input_dim:
    value: 784
learning_rate:
    value: 0.001
num_hidden_layers:
    value: 4
num_neurons:
    value: "128"
num_neurons_resolved:
    value: "128"
optimizer:
    value: adam
output_dim:
    value: 10
random_seed:
    value: 7
val_ratio:
    value: 0.1
weight_decay:
    value: 0.001
